## 317 - Corfidi Storm Motion Calculations in Python

[Youtube](https://www.youtube.com/watch?v=J-YHCcbCBD0)

In [1]:
from siphon.simplewebservice.wyoming import WyomingUpperAir
from metpy.units import pandas_dataframe_to_unit_arrays, units
from datetime import datetime
import pandas as pd

In [2]:
date = datetime(1997, 8, 16, 12)
station = 'DTX'
df = WyomingUpperAir.request_data(date, station)

In [3]:
df.head()

,pressure,height,temperature,dewpoint,direction,speed,u_wind,v_wind,station,station_number,time,latitude,longitude,elevation,pw
0,970.0,329,20.8,20.0,260.0,9.0,8.863270,1.562834,DTX,72632,1997-08-16 12:00:00,42.7,-83.46,329.0,40.78
1,952.0,491,21.2,21.0,254.0,19.0,18.263972,5.237110,DTX,72632,1997-08-16 12:00:00,42.7,-83.46,329.0,40.78
2,944.0,564,22.4,19.2,252.0,23.0,21.874300,7.107391,DTX,72632,1997-08-16 12:00:00,42.7,-83.46,329.0,40.78
3,941.0,592,22.8,21.0,251.0,25.0,23.637964,8.139204,DTX,72632,1997-08-16 12:00:00,42.7,-83.46,329.0,40.78
4,939.0,610,22.7,21.0,250.0,26.0,24.432008,8.892524,DTX,72632,1997-08-16 12:00:00,42.7,-83.46,329.0,40.78

In [4]:
import metpy.calc as mpcalc

In [5]:
df = pandas_dataframe_to_unit_arrays(df)

In [6]:
df

{'pressure': array([970. , 952. , 944. , 941. , 939. , 925. , 906.8, 897. , 875.5,
        850. , 815.5, 797. , 786.8, 784. , 770. , 758.9, 731.7, 728. ,
        722. , 700. , 672. , 654.7, 607.2, 575. , 562.9, 562. , 556. ,
        551. , 528. , 521. , 500. , 481.8, 456. , 416. , 400. , 394.1,
        341. , 330. , 319.5, 300. , 280.4, 273. , 256.4, 250. , 200. ,
        186. , 184.7, 150. , 140. , 125. , 100. ,  98.9,  97.5,  92.8,
         84.2,  76.3,  70. ,  69.1,  50. ,  47. ,  37. ,  33.7,  30. ,
         27.9,  20.1,  20. ,  18.3,  15.6,  11.6,  10. ,   8.9,   8.5]) <Unit('hectopascal')>,
 'height': array([  329,   491,   564,   592,   610,   741,   914,  1009,  1219,
         1475,  1829,  2025,  2134,  2164,  2316,  2438,  2743,  2786,
         2855,  3111,  3447,  3658,  4267,  4707,  4877,  4889,  4975,
         5046,  5383,  5488,  5810,  6096,  6520,  7216,  7510,  7620,
         8681,  8916,  9144,  9590, 10058, 10242, 10668, 10840, 12300,
        12759, 12802, 14120, 14546, 15240, 16610, 16678, 16764, 17069,
        17678, 18288, 18820, 18898, 20940, 21336, 22860, 23470, 24210,
        24689, 26822, 26860, 27432, 28502, 30480, 31480, 32309, 32590]) <Unit('meter')>,
 'temperature': array([ 20.8,  21.2,  22.4,  22.8,  22.7,  22. ,  21.7,  21.6,  20.2,
         18.6,  16.1,  14.8,  13.9,  13.6,  13.2,  12.5,  10.7,  10.4,
          9.8,   7.6,   5.6,   4.5,   1.4,  -0.9,  -2.6,  -2.7,  -3.5,
         -3.7,  -4.9,  -4.7,  -6.9,  -9. , -12.1, -15.9, -18.5, -19.4,
        -27.7, -29.5, -31.3, -34.9, -37.8, -38.9, -42.3, -43.7, -53.7,
        -55.7, -55.9, -61.7, -63.5, -63.8, -64.5, -64.7, -64.5, -63.6,
        -61.9, -60.2, -58.7, -58.6, -57.1, -56.5, -54.2, -53.2, -52.1,
        -51.3, -48. , -47.9, -47.6, -47.1, -43.5, -41.7, -38.9, -37.9]) <Unit('degree_Celsius')>,
 'dewpoint': array([ 20. ,  21. ,  19.2,  21. ,  21. ,  21. ,  21.1,  21.1,  18.4,
         15.2,  11.1,   8.8,   9.6,   9.8,   3.2,   2.7,   1.6,   1.4,
          5.2,   3.8,  -2.4,  -4.5, -10.5, -14.9, -12.8, -12.7,  -7.1,
         -6. , -10.9, -24.7, -34.9, -37. , -40.1, -39.9, -40.5, -40.9,
        -44.7, -35.5, -36.5, -38.4, -44.5, -46.9, -50.3, -51.7, -61.7,
        -63.7, -63.9, -69.7, -70.5, -70.8, -71.5, -71.7, -71.5, -71. ,
        -69.8, -68.7, -67.7, -67.7, -67.1, -67.5, -68.9, -69.4, -70.1,
        -71.2, -75.8, -75.9, -75.6, -75.1, -72.8, -71.7, -69.6, -68.9]) <Unit('degree_Celsius')>,
 'direction': array([260., 254., 252., 251., 250., 250., 260., 262., 265., 270., 270.,
        267., 265., 265., 262., 260., 255., 255., 255., 255., 255., 255.,
        265., 272., 275., 275., 274., 273., 270., 268., 265., 265., 261.,
        253., 250., 250., 247., 246., 245., 250., 260., 260., 260., 255.,
        255., 250., 250., 250., 250., 250., 250., 250., 250., 260., 270.,
        245., 245., 245.,  95., 105., 115., 100.,  75.,  70., 100.,  95.,
         95.,  93.,  90.,  80.,  80.,  nan]) <Unit('degree')>,
 'speed': array([ 9., 19., 23., 25., 26., 26., 27., 28., 29., 31., 31., 33., 34.,
        34., 35., 36., 38., 38., 38., 39., 41., 43., 41., 42., 42., 42.,
        42., 43., 44., 45., 46., 47., 48., 49., 49., 49., 48., 48., 48.,
        50., 49., 51., 54., 57., 70., 73., 73., 64., 61., 46., 38., 38.,
        38., 36., 20., 12., 14., 14.,  5.,  7., 11., 14., 15., 17., 22.,
        22., 24., 24., 25., 34., 35., nan]) <Unit('knot')>,
 'u_wind': array([  8.86326978,  18.26397222,  21.87429987,  23.63796439,
         24.43200814,  24.43200814,  26.58980933,  27.72750592,
         28.88964624,  31.        ,  31.        ,  32.95477465,
         33.87061974,  33.87061974,  34.65938241,  35.45307911,
         36.7051814 ,  36.7051814 ,  36.7051814 ,  37.67110723,
         39.60295888,  41.53481053,  40.84398262,  41.97441473,
         41.84017732,  41.84017732,  41.89769011,  42.94106999,
         44.        ,  44.97258722,  45.82495611,  46.82115081,
         47.40904035,  46.85893304,  46.04493842,  46.04493842,
         44.18423297,  43.85018197,  43.50277378,  46.98463104,
         48.2555799 ,  50.2251954 ,  53.17961866,  55.0577721 ,
         67.61480784,  68.59756132,  68.59756132,  60.14032773,
         57.32124987,  43.22586056,  35.70831959,  35.70831959,
         35.70831959,  35.45307911,  20.        ,  10.87569344,
         12.68830902,  12.68830902,  -4.98097349,  -6.76148078,
         -9.96938566, -13.78730854, -14.48888739, -15.97477455,
        -21.66577057, -21.91628336, -23.90867275, -23.96710883,
        -25.        , -33.4834636 , -34.46827136,          nan]) <Unit('knot')>,
 'v_wind': array([ 1.56283360e+00,  5.23710976e+00,  7.10739087e+00,  8.13920386e+00,
         8.89252373e+00,  8.89252373e+00,  4.68850080e+00,  3.89684683e+00,
         2.52751654e+00,  5.69460762e-15,  5.69460762e-15,  1.72708656e+00,
         2.96329525e+00,  2.96329525e+00,  4.87105853e+00,  6.25133440e+00,
         9.83512371e+00,  9.83512371e+00,  9.83512371e+00,  1.00939428e+01,
         1.06115808e+01,  1.11292189e+01,  3.57338545e+00, -1.46577886e+00,
        -3.66054120e+00, -3.66054120e+00, -2.92977190e+00, -2.25044612e+00,
         8.08266887e-15,  1.57047735e+00,  4.00916417e+00,  4.09631991e+00,
         7.50885432e+00,  1.43262135e+01,  1.67589870e+01,  1.67589870e+01,
         1.87550942e+01,  1.95233589e+01,  2.02856766e+01,  1.71010072e+01,
         8.50876071e+00,  8.85605706e+00,  9.37700159e+00,  1.47526856e+01,
         1.81173332e+01,  2.49674705e+01,  2.49674705e+01,  2.18892892e+01,
         2.08632287e+01,  1.57329266e+01,  1.29967654e+01,  1.29967654e+01,
         1.29967654e+01,  6.25133440e+00,  3.67394040e-15,  5.07141914e+00,
         5.91665566e+00,  5.91665566e+00,  4.35778714e-01,  1.81173332e+00,
         4.64880088e+00,  2.43107449e+00, -3.88228568e+00, -5.81434244e+00,
         3.82025991e+00,  1.91742634e+00,  2.09173783e+00,  1.25606295e+00,
        -1.53080850e-15, -5.90403804e+00, -6.07768622e+00,             nan]) <Unit('knot')>,
 'station': array(['DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX',
        'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX', 'DTX'],
       dtype=object),
 'station_number': array([72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632,
        72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632, 72632]),
 'time': array(['1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000',
        '1997-08-16T12:00:00.000000', '1997-08-16T12:00:00.000000'],
       dtype='datetime64[us]'),
 'latitude': array([42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7,
        42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7,
        42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7,
        42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7,
        42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7,
        42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7, 42.7,
        42.7, 42.7, 42.7, 42.7, 42.7, 42.7]) <Unit('degree')>,
 'longitude': array([-83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46,
        -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46, -83.46]) <Unit('degree')>,
 'elevation': array([329., 329., 329., 329., 329., 329., 329., 329., 329., 329., 329.,
        329., 329., 329., 329., 329., 329., 329., 329., 329., 329., 329.,
        329., 329., 329., 329., 329., 329., 329., 329., 329., 329., 329.,
        329., 329., 329., 329., 329., 329., 329., 329., 329., 329., 329.,
        329., 329., 329., 329., 329., 329., 329., 329., 329., 329., 329.,
        329., 329., 329., 329., 329., 329., 329., 329., 329., 329., 329.,
        329., 329., 329., 329., 329., 329.]) <Unit('meter')>,
 'pw': array([40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78,
        40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78, 40.78]) <Unit('millimeter')>}

In [7]:
motion = mpcalc.corfidi_storm_motion(df['pressure'], df['u_wind'], df['v_wind'])

In [8]:
motion

(array([8.91538027, 6.62860056]) <Unit('knot')>,
 array([48.83076054, 13.25720112]) <Unit('knot')>)

In [9]:
upwind = mpcalc.wind_direction(motion[0][0], motion[0][1])
downwind = mpcalc.wind_direction(motion[1][0], motion[1][1])

In [10]:
print(upwind, downwind)

233.36913393563546 degree 254.8107339513306 degree

In [11]:
print(mpcalc.wind_speed(motion[1][0], motion[1][1]))

50.59838491959225 knot

In [12]:
def get_downwind_for_case(date, station):
    """
    Get the Corfidi Downwind Propagation motion for a case.
    """
    df = WyomingUpperAir.request_data(date, station)
    df = pandas_dataframe_to_unit_arrays(df)
    motion = mpcalc.corfidi_storm_motion(df['pressure'], df['u_wind'], df['v_wind'])
    downwind_direction = mpcalc.wind_direction(motion[1][0], motion[1][1])
    downwind_speed = mpcalc.wind_speed(motion[1][0], motion[1][1])
    return downwind_direction, downwind_speed

In [13]:
get_downwind_for_case(date, station)

(array(254.81073395) <Unit('degree')>, 50.59838491959225 <Unit('knot')>)